image: Visual Studio 2019
init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true

build_script:
  - cmd: .\build.cmd --target NuGet

test: off

artifacts:
  - path: 'bin\*.nupkg'
    type: NuGetPackage